### PR TITLE
replaced links to  old RU CMS documentation with updated links

### PR DESCRIPTION
**Pull request by robertoostenveld**
I noticed that in the configurable content there were still a lot of links pointing to the old documentation. I replaced those with the corresponding URLs pointing to the new documentation.

### CODE REVIEW

**Comment by robertoostenveld** [comment]
just for reference: basically I searched for `www.ru.nl/donders/research/data` in the configurable content and replaced all (but one) URL.

In ram-nutshell.rst there is one link to <https://www.ru.nl/donders/research/data/presentations/> that I did not replace, since those pdf documents are not present in the new help system. I also don't think they should be copied there.

**Comment by robertoostenveld** [comment]
@jesask and @hurngchunlee can you please have a look at this. I am receiving complaints from external users that the documentation does not work, and I think this will fix it.

_PS it seems that all subsections under https://www.ru.nl/donders/research/research-data-management/ have been removed from RU CMS, hence the complaints that it does not work any more._

**Comment by hurngchunlee** [comment]
I have quickly merged it and pushed it to the production release.

**Comment by jesask** [comment]
Ok thanks, that works

**Pull request merged**
